const ON_ACTORS_LIST_FETCH_REQUEST = 'hof/ON_ACTORS_LIST_FETCH_REQUEST';
const ON_ACTORS_LIST_FETCH_SUCCESS = 'hof/ON_ACTORS_LIST_FETCH_SUCCESS';
const ON_ACTORS_LIST_FETCH_FAILURE = 'hof/ON_ACTORS_LIST_FETCH_FAILURE';

export {ON_ACTORS_LIST_FETCH_FAILURE, ON_ACTORS_LIST_FETCH_REQUEST, ON_ACTORS_LIST_FETCH_SUCCESS};
